comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

ignore:
  - "R/zzz.R"
  - "R/zzz_data.R"

codecov:
  token: 82202c8b-b550-48f0-8454-84a706600c83
